branches:
  only:
    - master
    - develop

notifications:
  email: false

language: node_js

node_js:
  - "8"
  - "7"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

after_success:
  - npm run codecov
